### ISSUE TITLE
Reorganize environment.yml files

### ISSUE THREAD

**Issue by jdhughes-usgs** [EC-USGS/pywatershed#165]
Since `pyproject.toml` has been setup to install required, lint, test, and optional dependencies a single development `environment.yml` should be created. 

- [X] The revised `environment.yml` should have all of the dependencies in` pyproject.toml`
- [X] The revised `environment.yml` should be in the root repo directory. 
- [ ] All of the other `environment.yml` files should be eliminated. 
- [X] README.md should be updated to reflect changes.
- [X] Should evaluate if `*.txt` equivalents of `environment.yml` are needed. Delete if not needed.

**Comment by jmccreight** [comment]
There is still a joint mf6/flopy development env file to be reconciled: pwsmf6nb.yml in the root dir.

**Comment by jmccreight** [comment]
The  pwsmf6nb.yml seems to no longer relevant, it was eliminated. 

We do, however, no hwave environment.yaml environment_w_jupyter.yaml where the former does not include jupyter dependencies because this causes problem with installation when using WholeTale.
