### ISSUE TITLE
Reorganize and thin notebooks

### ISSUE THREAD

**Issue by jdhughes-usgs** [EC-USGS/pywatershed#169]
Notebooks exist in multiple places in the repo (evaluation, examples). Also it is unclear if all of these are necessary. In a recent PR (#164) several notebooks were out of date with recent commits.

Notebooks should also be run as part of CI to ensure that can be run with the current version of pywatershed.

**Comment by jmccreight** [comment]
* Some notebooks are tested (the numbered ones). But the testing is not very robust. I'm going to look into better notebook tests.
* Related to the above, I may use frozen environments for notebook testing and periodically update the env. 
* The notebooks in the repo should be change to focus more on users. The existing notebooks focus more on developers. 
* I'm considering an external repo for more in-depth notebooks, including developer notebooks. This would have its own CI.

Any feedback on those points is appreciated.
