### ISSUE TITLE
examples/02_prms_legacy_models.ipynb

### ISSUE THREAD

**Issue by markstro-usgs** [EC-USGS/pywatershed#227]
I've been running the example 02_prms_legacy_models.ipynb notebooks from a pywatershed installation on my windows 10 machine (not Whole Tale). This isn't necessarily a showstopper for me, but I want to report this error:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[16], line 7
      1 submodel = pws.Model(
      2     submodel_processes,
      3     control=control,
      4     parameters=params,
      5 )
----> 7 pws.analysis.ModelGraph(
      8     submodel,
      9     hide_variables=not show_params,
     10     show_params=show_params,
     11     process_colors=palette,
     12 ).SVG(verbose=True, dpi=48)

File D:\PYWATERSHED\pywatershed\pywatershed\analysis\model_graph.py:120, in ModelGraph.SVG(self, verbose, dpi)
    118 if self.graph is None:
    119     self.build_graph()
--> 120 self.graph.write_svg(tmp_file, prog=["dot", f"-Gdpi={dpi}"])
    121 if verbose:
    122     print(f"Displaying SVG written to temp file: {tmp_file}")

File ~\AppData\Local\mambaforge\envs\pws\lib\site-packages\pydot.py:1743, in Dot.__init__.<locals>.new_method(path, f, prog, encoding)
   1739 def new_method(
   1740         path, f=frmt, prog=self.prog,
   1741         encoding=None):
   1742     """Refer to docstring of method `write.`"""
-> 1743     self.write(
   1744         path, format=f, prog=prog,
   1745         encoding=encoding)

File ~\AppData\Local\mambaforge\envs\pws\lib\site-packages\pydot.py:1828, in Dot.write(self, path, prog, format, encoding)
   1826         f.write(s)
   1827 else:
-> 1828     s = self.create(prog, format, encoding=encoding)
   1829     with io.open(path, mode='wb') as f:
   1830         f.write(s)

File ~\AppData\Local\mambaforge\envs\pws\lib\site-packages\pydot.py:1956, in Dot.create(self, prog, format, encoding)
   1944     message = (
   1945         '"{prog}" with args {arguments} returned code: {code}\n\n'
   1946         'stdout, stderr:\n {out}\n{err}\n'
   (...)
   1952         err=stderr_data,
   1953     )
   1954     print(message)
-> 1956 assert process.returncode == 0, (
   1957         '"{prog}" with args {arguments} returned code: {code}'.format(
   1958             prog=prog,
   1959             arguments=arguments,
   1960             code=process.returncode,
   1961         )
   1962     )
   1964 return stdout_data

AssertionError: "dot" with args ['-Tsvg', '-Gdpi=48', 'C:\\Users\\markstro\\AppData\\Local\\Temp\\1\\tmprshir33o'] returned code: 3221225477

**Comment by jmccreight** [comment]
Thanks @markstro-usgs, 
This or very similar is a known issue on Mac ARM processors. I have filed a bug report with graphviz on that: https://gitlab.com/graphviz/graphviz/-/issues/2400
It is new to me that this fails on windows 10, i believe it works fine on my windows machine. We could add this to the bug report but we might have to parse it a bit more before hand.

**Comment by jmccreight** [comment]
See #229 for the plots as they should work.
