### ISSUE TITLE
examples/01_multi-process_models.ipynb

### ISSUE THREAD

**Issue by wkitlasten** [EC-USGS/pywatershed#229]
Excited to see this work, ultimately to use with MF6 api. Trying to get oriented but I'm running into an issue that I do not comprehend. Any suggestions?

![image](https://github.com/EC-USGS/pywatershed/assets/14982084/4f220462-7b4b-46a8-85ee-90a9642e83e0)

**Comment by jmccreight** [comment]
Hi Wes, 
I believe this is the same as #227. It is an issue with with graphviz/dot. I have a bug report in on this linked in #227.

Are you on windows?

You don't need the graph to proceed. I will paste the graphs for all the notebooks into this issue so folks with the problem can see the output here. But no subsequent cells rely on the cells that are failing. (BTW, this will execute on WholeTale if you want to run it). 

Thanks,

some key words for future searches
assertion failed error
modelgraph
palette
cdt.c

**Comment by jmccreight** [comment]
Figures for notebook examples/01_multi-process_models.ipynb
![graphviz_01_full_model](https://github.com/EC-USGS/pywatershed/assets/12465248/7813cba0-343c-4bf1-9b15-6ed92930f288)
![graphviz_01_sub_model](https://github.com/EC-USGS/pywatershed/assets/12465248/e0902e7f-ac69-488c-8719-858315d45e7c)

**Comment by jmccreight** [comment]
Figures for examples/02_prms_legacy_models.ipynb (these are the same, ha!)
![graphviz_02_full_model](https://github.com/EC-USGS/pywatershed/assets/12465248/8ae2ee77-24ea-4d48-b55c-cace3113989f)
![graphviz_02_sub_model](https://github.com/EC-USGS/pywatershed/assets/12465248/c2b57ad7-c597-427b-9f9d-b9cd9e51c00d)

**Comment by wkitlasten** [comment]
Apologies for not realizing it was covered in #227
