### ISSUE TITLE
.to_xr_ds() error with legacy params

### ISSUE THREAD

**Issue by jdickins-usgs** [EC-USGS/pywatershed#289]
ValueError: Variable 'den_init': Could not convert tuple of form (dims, data[, attrs, encoding]): ((), array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,

params = pws.parameters.PrmsParameters.load(input_dir / "myparam.param")
params_snow = params.subset(pws.PRMSSnow.get_parameters())
---> 13 param_ds = params_snow.to_xr_ds()

ValueError: Variable 'den_init': Could not convert tuple of form (dims, data[, attrs, encoding]): ((), array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,

This parameter was dimensioned nhru, and each value was the same. Error didn't happen when the parameter was defined with dimension 'one' using just the same value. No errors for other parameters dimensioned as nhru.

**Comment by jdickins-usgs** [comment]
error came up for parameters den_init, den_max, settle_const

**Comment by jmccreight** [comment]
fixed earlier by 
https://github.com/EC-USGS/pywatershed/commit/9335b8abd5ec97e813ab50e6425622aebbc9da5d
and #288
